FROM gcc

WORKDIR /app

CMD ["/bin/bash"]

# docker build -t gcc .
# docker run -it --rm -v ${PWD}:/app gcc

# gcc main.c -pthread -lrt && ./a.out

# tar -zxvf data.tar.gz
# gcc apache_main.c -lapr-1

# https://stackoverflow.com/questions/7738546/how-to-set-a-timeout-for-a-function-in-c
